config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get "/about" => "home#about"
  get "/home" => "home#index"
  get "/posts/search" => "posts#search"
  # get "/sessions/forgot_password" => "sessions#forgot_password"

  resources :posts do
    resources :comments, only: [:index, :create, :destroy]
    # get "/comments/:id" => "posts#show"
    # post "/" => "posts#index", on: :collection
    resources :favorites, only: [:create, :destroy]
  end
  resources :favorites, only: [:index]
  resources :comments, only: [:edit, :update]

  resources :users, only: [:new, :create, :edit, :update, :show] do
    get "/change_password" => "users#change_password"
  end
  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
    get :forgot_password, on: :collection
  end

  resources :password_resets

  root "home#index"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :posts
    end
  end

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user

  def index
    @posts = current_user.favorite_posts.page params[:page]
  end

  def create
    @post = Post.friendly.find params[:post_id]
    @favorite = Favorite.new(post: @post, user: current_user)
    respond_to do |format|
      if @favorite.save
        format.html { redirect_to @post, notice: "Post added to favorites!" }
        format.js { render :create_success }
      else
        format.html { redirect_to @post, notice: "Post already in favorites!" }
        format.js { render :create_failure }
      end
    end
  end

  def destroy
    @post = Post.friendly.find params[:post_id]
    @favorite = current_user.favorites.find params[:id]
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to @post, notice: "Post removed from favorites." }
      format.js { render }
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_post_favorite.html.erb
<% favorite = @post.favorite_for current_user %>
<% if favorite %>
  <%= link_to fa_icon("heart"), post_favorite_path(@post, favorite), method: :delete, remote: true, class: "fa-icon-link unfav" %>
<% else %>
  <%= link_to fa_icon("heart-o"), post_favorites_path(@post), method: :post, remote: true, class: "fa-icon-link fav" %>
<% end %>

app/views/favorites/create_failure.js.erb
alert("didn't work!");

app/views/favorites/create_success.js.erb
$('#favorites').html("<%= j render 'post_favorite' %>");

app/views/favorites/destroy.js.erb
$('#favorites').html("<%= j render 'post_favorite' %>")

app/views/favorites/index.html.erb
<h1>Favorite Posts</h1>

<% @posts.each do |post| %>
  <div>
     <h3><%= link_to post.title, post_path(post) %></h3>
     <hr>
  </div>
<% end %>

<div class="text-center"><%= paginate @posts, theme: 'bootstrap3' %></div>