config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get "/about" => "home#about"
  get "/home" => "home#index"
  get "/posts/search" => "posts#search"
  # get "/sessions/forgot_password" => "sessions#forgot_password"

  resources :posts do
    resources :comments, only: [:index, :create, :destroy]
    # get "/comments/:id" => "posts#show"
    # post "/" => "posts#index", on: :collection
    resources :favorites, only: [:create, :destroy]
  end
  resources :favorites, only: [:index]
  resources :comments, only: [:edit, :update]

  resources :users, only: [:new, :create, :edit, :update, :show] do
    get "/change_password" => "users#change_password"
  end
  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
    get :forgot_password, on: :collection
  end

  resources :password_resets

  root "home#index"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :posts
    end
  end

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post

  has_secure_password
  validates :password, length: {minimum: 6}, on: :create
  validates :first_name, presence: true, on: :create
  validates :last_name, presence: true, on: :create
  validates :email, presence: true, uniqueness: true,
            format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
            on: :create,
            unless: :from_oauth?

  before_create :generate_api_key
  serialize :twitter_raw_data, Hash


   def full_name
     "#{first_name} #{last_name}".titleize
   end

   def send_password_reset
     generate_token(:password_reset_token)
     self.password_reset_sent_at = Time.zone.now
     save!
     UserMailer.password_reset(self).deliver_now
   end

   def generate_token(column)
     begin
       self[column] = SecureRandom.urlsafe_base64
     end while User.exists?(column => self[column])
   end

  def self.find_twitter_user(omniauth_data)
    where(provider: "twitter", uid: omniauth_data["uid"]).first
  end

  def self.create_from_twitter(twitter_data)
    name = twitter_data["info"]["name"].split(" ")
    user = User.create(provider: "twitter",
    uid: twitter_data["uid"],
    first_name: name[0],
    last_name: name[1],
    password: SecureRandom.hex(16),
    twitter_consumer_token: twitter_data["credentials"]["token"],
    twitter_consumer_secret: twitter_data["credentials"]["secret"],
    twitter_raw_data: twitter_data)
  end


  private

  def from_oauth?
    uid.present? && provider.present? && provider == "twitter"
  end

  def generate_api_key
    self.api_key = SecureRandom.hex(32)
    while User.exists?(api_key: self.api_key)
      self.api_key = SecureRandom.hex(32)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :change_password, :check_password]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      sign_in(@user)
      redirect_to root_path, notice: "Sign up successful!"
    else
      flash[:alert] = "Sign up unsuccessful."
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if check_password
      if @user.update user_params
        redirect_to user_path(@user), notice: "Profile updated successfully."
      else
        flash[:notice] = "Profile not updated."
        @changing_password ? (render :change_password) : (render :edit)
      end
    else
      flash[:alert] = "Wrong credentials!"
      @changing_password ? (render :change_password) : (render :edit)
    end
  end

  def change_password
  end

  private

  def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def find_user
    @user = User.find current_user.id
  end

  def check_password
    authentic_password = @user.authenticate(params[:user]["current_password"])
    different_password = params[:user]["current_password"] != params[:user]["password"]
    @changing_password = params[:user]["password"]
    @changing_password ? (authentic_password && different_password) : authentic_password
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= simple_form_for @user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <% if user_signed_in?%>
    <%= f.input :current_password %>
  <% else %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  <% end %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/users/change_password.html.erb
<h1>Change Password</h1>

<%= form_for @user do |f| %>
  <%= content_tag(:div, class: "form-group") do %>
    <%= f.label :current_password %>
    <%= f.password_field :current_password, class: "form-control" %>
  <% end %>
  <%= content_tag(:div, class: "form-group") do %>
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  <% end %>
  <%= content_tag(:div, class: "form-group") do %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  <% end %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render "form" %>

<%= link_to "Change Password", user_change_password_path(@user) %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "form" %>

app/views/users/show.html.erb
<h1>Your Profile</h1>

<p>First Name: <%= @user.first_name %></p>
<p>Last Name: <%= @user.last_name %></p>
<p>Email: <%= @user.email %></p>

<%= link_to "Edit Profile", edit_user_path(@user) %>