config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get "/about" => "home#about"
  get "/home" => "home#index"
  get "/posts/search" => "posts#search"
  # get "/sessions/forgot_password" => "sessions#forgot_password"

  resources :posts do
    resources :comments, only: [:index, :create, :destroy]
    # get "/comments/:id" => "posts#show"
    # post "/" => "posts#index", on: :collection
    resources :favorites, only: [:create, :destroy]
  end
  resources :favorites, only: [:index]
  resources :comments, only: [:edit, :update]

  resources :users, only: [:new, :create, :edit, :update, :show] do
    get "/change_password" => "users#change_password"
  end
  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
    get :forgot_password, on: :collection
  end

  resources :password_resets

  root "home#index"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :posts
    end
  end

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= content_tag(:nav, class: "navbar navbar-default") do %>
    <%= content_tag(:div, class: "container-fluid") do %>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", home_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "All Posts", posts_path %></li>
          <li><%= link_to "Favorite Posts", favorites_path %></li>
          <li><%= link_to "New Post", new_post_path %></li>
        </ul>
        <%= form_tag("/posts", method: "get", class: "navbar-form navbar-left") do %>
          <%= content_tag(:div, class: "form-group") do %>
            <%= text_field_tag(:q, session[:q], class: "form-control") %>
            <%= submit_tag("Search Posts", class: "btn btn-primary") %>
          <% end %>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Welcome #{current_user.first_name} #{current_user.last_name}!", user_path(current_user) %></li>
            <li><%= link_to "Log Out", sessions_path, method: :delete, data: {confirm: "Are you sure you want to log out?"} %></li>
          <% else %>
            <li><%= link_to "Sign In", new_session_path %></li>
            <li><%= link_to "Sign in with Twitter", sign_in_with_twitter_path %></li>
            <li><button class="btn btn-default navbar-btn"><%= link_to "Sign Up", new_user_path %></button></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>

<div class="container-fluid">
  <% if notice %>
    <div class="alert alert-success"><%= notice %></div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger"><%= alert %></div>
  <% end %>
</div>

<%= content_tag(:div, class: "container-fluid") do %>
  <%= content_tag(:div, class: "row") do %>
    <%= content_tag(:div, class: "col-sm-12") do %>
      <%= yield %>
    <% end %>
  <% end %>
<% end %>

</body>
</html>